# Generated by Django 5.0.7 on 2025-06-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('persona_natural', 'Persona Natural'), ('entidad_publica', 'Entidad Pública'), ('ong', 'ONG'), ('otro', 'Otro')], default='empresa', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('pendiente', 'Pendiente de Aprobación'), ('rechazada', 'Rechazada'), ('en_revision', 'En Revisión')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_proxima_dd', models.DateField(blank=True, help_text='Fecha de la próxima renovación de debida diligencia', null=True, verbose_name='Próxima Debida Diligencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrapartes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Contraparte',
                'verbose_name_plural': 'Contrapartes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('documento_identidad', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula de Ciudadanía'), ('pasaporte', 'Pasaporte'), ('cedula_extranjeria', 'Cédula de Extranjería'), ('nit', 'NIT'), ('otro', 'Otro')], default='cedula', max_length=20, verbose_name='Tipo de documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('rol', models.CharField(choices=[('ceo', 'CEO'), ('accionista', 'Accionista'), ('director', 'Director'), ('representante_legal', 'Representante Legal'), ('beneficiario_final', 'Beneficiario Final'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Rol en la organización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='contrapartes.contraparte', verbose_name='Contraparte')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['nombre'],
                'unique_together': {('contraparte', 'documento_identidad')},
            },
        ),
    ]
