# Generated by Django 5.0.7 on 2025-06-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='miembro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='miembro',
            name='categoria',
            field=models.CharField(choices=[('shareholder', 'Shareholder'), ('executive', 'Executive'), ('ultimate_beneficial_owner', 'Ultimate Beneficial Owner'), ('board_of_director', 'Board of Director')], default='shareholder', max_length=30, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='numero_identificacion',
            field=models.CharField(default='000000000', max_length=50, verbose_name='Número de identificación'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='tipo_persona',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=20, verbose_name='Tipo de persona'),
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='documento_identidad',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='tipo_documento',
        ),
    ]
