# Generated by Django 5.0.7 on 2025-06-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0002_alter_miembro_unique_together_miembro_categoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='miembro',
            unique_together={('contraparte', 'numero_identificacion')},
        ),
    ]
