# Generated by Django 5.0.7 on 2025-08-25 22:31

import django.db.models.deletion
from django.db import migrations, models


def copy_tipo_to_temp_and_convert_to_fk(apps, schema_editor):
    """Copy existing tipo values to tipo_temp and convert to ForeignKey references"""
    Documento = apps.get_model('contrapartes', 'Documento')
    TipoDocumento = apps.get_model('contrapartes', 'TipoDocumento')
    
    # Mapping of old string values to new codes
    tipo_mapping = {
        'dd': 'cedula',  # Due Diligence mapped to cedula as fallback
        'contrato': 'contrato',
        'certificacion': 'certificacion',
        'otro': 'otro'
    }
    
    # Get the "otro" type as fallback
    tipo_otro = TipoDocumento.objects.filter(codigo='otro').first()
    
    for documento in Documento.objects.all():
        # Copy current tipo to tipo_temp
        documento.tipo_temp = documento.tipo
        
        # Find the corresponding TipoDocumento
        codigo_nuevo = tipo_mapping.get(documento.tipo, 'otro')
        tipo_documento = TipoDocumento.objects.filter(codigo=codigo_nuevo).first()
        
        if not tipo_documento:
            tipo_documento = tipo_otro
            
        # We'll set this in the next step after the field is converted
        documento.save()


def reverse_copy(apps, schema_editor):
    """Reverse the copy operation"""
    Documento = apps.get_model('contrapartes', 'Documento')
    for documento in Documento.objects.all():
        documento.tipo = documento.tipo_temp
        documento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0006_create_tipos_documento_step1'),
    ]

    operations = [
        # Step 1: Copy current tipo values to tipo_temp
        migrations.RunPython(
            copy_tipo_to_temp_and_convert_to_fk,
            reverse_copy,
        ),
        
        # Step 2: Remove the old tipo field
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        
        # Step 3: Add the new ForeignKey tipo field
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(
                help_text='Tipo de documento', 
                limit_choices_to={'activo': True}, 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='documentos', 
                to='contrapartes.tipodocumento', 
                verbose_name='Tipo de documento',
                null=True  # Temporarily allow null
            ),
        ),
    ]
