# Generated by Django 5.0.7 on 2025-08-26 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0008_finalize_tipo_conversion_step3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido del comentario', verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('editado', models.BooleanField(default=False, help_text='Indica si el comentario ha sido editado', verbose_name='Editado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='contrapartes.contraparte', verbose_name='Contraparte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_contrapartes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
