# Generated by Django 5.0.7 on 2025-08-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0009_add_comentario_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraparte',
            name='business_address',
            field=models.TextField(blank=True, help_text='Primary business operating address', null=True, verbose_name='Business Address'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='company_incorporation_registration',
            field=models.CharField(blank=True, help_text='Registration or incorporation number', max_length=100, null=True, verbose_name='Company Incorporation/Registration'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='company_nature_business',
            field=models.TextField(blank=True, help_text="Description of the company's business activities and nature", null=True, verbose_name='Company Nature and Type of Business'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='company_website',
            field=models.URLField(blank=True, help_text='Official company website URL', null=True, verbose_name='Company Website'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email address', max_length=254, null=True, verbose_name='Contact E-mail Address'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='contact_telephone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=50, null=True, verbose_name='Contact Telephone Number'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='date_incorporation',
            field=models.DateField(blank=True, help_text='Date when the company was legally incorporated', null=True, verbose_name='Date of Incorporation/Registration'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='domicile',
            field=models.CharField(blank=True, help_text='Legal domicile or jurisdiction of incorporation', max_length=100, null=True, verbose_name='Domicile'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='external_auditors',
            field=models.TextField(blank=True, help_text="Details of the company's external auditing firm", null=True, verbose_name='Name and Address of External Auditors'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='full_company_name',
            field=models.CharField(blank=True, help_text='Complete legal name of the company', max_length=255, null=True, verbose_name='Full Company Name'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='home_regulatory_body',
            field=models.CharField(blank=True, help_text='Primary regulatory authority overseeing the company', max_length=255, null=True, verbose_name='Home Regulatory Body or Supervisory Authority'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='is_holding_company',
            field=models.BooleanField(blank=True, help_text='Whether the company operates as a holding company', null=True, verbose_name='Is the Company a Holding Company?'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='is_licensed_by_regulatory_body',
            field=models.BooleanField(blank=True, help_text='Whether the company holds necessary regulatory licenses', null=True, verbose_name='Is the company licensed by the Regulatory Body?'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='is_publicly_listed',
            field=models.BooleanField(blank=True, help_text='Whether the company is publicly traded', null=True, verbose_name='Is the Company publicly listed?'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, help_text='Current number of employees', null=True, verbose_name='Number of Employees'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='publicly_listed_country',
            field=models.CharField(blank=True, help_text='Country where the company is publicly listed', max_length=100, null=True, verbose_name='Country of public listing'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='registered_address',
            field=models.TextField(blank=True, help_text='Official registered address of the company', null=True, verbose_name='Registered Address'),
        ),
        migrations.AddField(
            model_name='contraparte',
            name='trading_name',
            field=models.CharField(blank=True, help_text='Commercial or trade name if different from legal name', max_length=255, null=True, verbose_name='Trading Name'),
        ),
        migrations.AlterField(
            model_name='contraparte',
            name='nacionalidad',
            field=models.CharField(blank=True, help_text='Legacy field - use domicile instead', max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='contraparte',
            name='nombre',
            field=models.CharField(blank=True, help_text='Legacy field - use full_company_name instead', max_length=255, null=True, verbose_name='Nombre'),
        ),
    ]
