# Generated by Django 5.0.7 on 2025-08-27 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0010_contraparte_business_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoContraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único para identificar el estado (ej: activa, pendiente, etc.)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del estado de contraparte', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del estado de contraparte', null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6B7280', help_text='Color hexadecimal para mostrar el estado (ej: #10B981 para verde)', max_length=7, verbose_name='Color')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este estado está disponible para contrapartes', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_contraparte_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Estado de Contraparte',
                'verbose_name_plural': 'Estados de Contraparte',
                'ordering': ['nombre'],
            },
        ),
    ]
