# Generated by Django 5.0.7 on 2025-08-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0012_auto_20250827_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraparte',
            name='estado_nuevo',
            field=models.ForeignKey(blank=True, help_text='Estado de la contraparte', limit_choices_to={'activo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrapartes', to='contrapartes.estadocontraparte', verbose_name='Estado Nuevo'),
        ),
    ]
