# Generated by Django 5.0.7 on 2025-08-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0014_auto_20250827_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraparte',
            name='estado',
            field=models.CharField(default='pendiente', help_text='Legacy field - use estado_nuevo instead', max_length=20, verbose_name='Estado (Legacy)'),
        ),
        migrations.AlterField(
            model_name='contraparte',
            name='estado_nuevo',
            field=models.ForeignKey(blank=True, help_text='Estado de la contraparte', limit_choices_to={'activo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrapartes', to='contrapartes.estadocontraparte', verbose_name='Estado'),
        ),
    ]
