# Generated by Django 5.0.7 on 2025-08-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0015_remove_legacy_estado_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraparte',
            name='estado',
        ),
    ]
