# Generated by Django 5.2.4 on 2025-08-27 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0016_remove_legacy_estado_field_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificacionInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificacion', models.CharField(help_text='Nombre de la agencia o estándar de certificación', max_length=255, verbose_name='Nombre de la Certificación')),
                ('codigo_certificacion', models.CharField(blank=True, help_text='Código único de la certificación', max_length=100, null=True, verbose_name='Código de Certificación')),
                ('calificacion', models.CharField(choices=[('AAA', 'AAA - Máxima calificación'), ('AA', 'AA - Calificación muy alta'), ('A', 'A - Calificación alta'), ('BBB', 'BBB - Calificación media-alta'), ('BB', 'BB - Calificación media'), ('B', 'B - Calificación media-baja'), ('CCC', 'CCC - Calificación baja'), ('CC', 'CC - Calificación muy baja'), ('C', 'C - Calificación mínima'), ('D', 'D - En default'), ('NR', 'NR - No calificado')], help_text='Calificación otorgada por la agencia', max_length=3, verbose_name='Calificación')),
                ('outlook', models.CharField(choices=[('positive', 'Positivo'), ('stable', 'Estable'), ('negative', 'Negativo'), ('developing', 'En desarrollo'), ('NR', 'No calificado')], help_text='Perspectiva futura de la calificación', max_length=20, verbose_name='Outlook')),
                ('fecha_emision', models.DateField(help_text='Fecha en que se otorgó la certificación', verbose_name='Fecha de Emisión')),
                ('fecha_expiracion', models.DateField(blank=True, help_text='Fecha en que expira la certificación (opcional)', null=True, verbose_name='Fecha de Expiración')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre la certificación', null=True, verbose_name='Descripción')),
                ('url_certificacion', models.URLField(blank=True, help_text='Enlace a la página oficial de la certificación', null=True, verbose_name='URL de la Certificación')),
                ('documento_soporte', models.FileField(blank=True, help_text='Documento que respalda la certificación', null=True, upload_to='certificaciones/', verbose_name='Documento de Soporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones_internacionales', to='contrapartes.contraparte', verbose_name='Contraparte')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Certificación Internacional',
                'verbose_name_plural': 'Certificaciones Internacionales',
                'ordering': ['-fecha_emision'],
                'unique_together': {('contraparte', 'codigo_certificacion')},
            },
        ),
    ]
