# Generated by Django 5.2.4 on 2025-08-28 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0017_certificacioninternacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la agencia o entidad calificadora', max_length=255, verbose_name='Nombre del Calificador')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificadores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Calificador',
                'verbose_name_plural': 'Calificadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Outlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlook', models.CharField(help_text='Tipo de outlook (ej: Positivo, Estable, Negativo)', max_length=50, verbose_name='Outlook')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlooks_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Outlook',
                'verbose_name_plural': 'Outlooks',
                'ordering': ['outlook'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(help_text='Calificación otorgada (ej: AAA, AA, A, BBB, etc.)', max_length=10, verbose_name='Calificación')),
                ('fecha', models.DateTimeField(help_text='Fecha de la calificación', verbose_name='Fecha')),
                ('documento_soporte', models.FileField(blank=True, help_text='Documento que respalda la calificación', null=True, upload_to='calificaciones/', verbose_name='Documento de Soporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='contrapartes.contraparte', verbose_name='Contraparte')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('calificador', models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='contrapartes.calificador', verbose_name='Calificador')),
                ('outlook', models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='contrapartes.outlook', verbose_name='Outlook')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='CertificacionInternacional',
        ),
    ]
