# Generated by Django 5.2.4 on 2025-08-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0018_calificador_outlook_calificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='nombre',
        ),
    ]
