# Generated by Django 5.2.4 on 2025-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0019_remove_nombre_from_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='es_pep',
            field=models.BooleanField(default=False, help_text='Indica si esta persona es una Persona Políticamente Expuesta', verbose_name='PEP (Politically Exposed Person)'),
        ),
    ]
