# Generated by Django 5.2.4 on 2025-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0020_add_pep_field_to_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='posicion_pep',
            field=models.CharField(blank=True, help_text='Cargo o posición política que ocupa o ha ocupado la persona', max_length=255, null=True, verbose_name='Posición como PEP'),
        ),
    ]
