# Generated by Django 5.0.7 on 2025-08-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0021_add_pep_position_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento (opcional)', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
