# Generated by Django 5.0.7 on 2025-08-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0022_make_fecha_nacimiento_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['categoria', '-fecha_subida'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('compliance', 'Compliance'), ('general_financial', 'General and Financial Information'), ('opportunities', 'Opportunities'), ('itico_requested', 'Information Requested from ITICO')], default='compliance', help_text='Categoría del documento para agrupación', max_length=20, verbose_name='Categoría'),
        ),
    ]
