# Generated by Django 5.0.7 on 2025-08-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0023_add_categoria_to_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='porcentaje_participacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de participación o propiedad (para shareholders y board of directors)', max_digits=5, null=True, verbose_name='% Participación'),
        ),
    ]
