# Generated by Django 5.0.7 on 2025-08-29 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0024_add_porcentaje_participacion_to_miembro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='porcentaje_participacion',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
    ]
