# Generated by Django 5.0.7 on 2025-09-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0025_alter_documento_options_remove_documento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.CharField(blank=True, choices=[('compliance', 'Compliance'), ('general_financial', 'General and Financial Information'), ('opportunities', 'Opportunities'), ('info_requested', 'Information Requested from ITICO')], help_text='Categoría del documento', max_length=50, null=True, verbose_name='Categoría'),
        ),
    ]
