# Generated by Django 5.0.7 on 2025-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0026_documento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('compliance', 'Compliance'), ('general_financial', 'General and Financial Information'), ('opportunities', 'Opportunities'), ('info_requested', 'Information Requested from ITICO')], default='compliance', help_text='Categoría del documento', max_length=20, verbose_name='Categoría'),
        ),
    ]
