# Generated by Django 5.0.7 on 2025-09-02 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0027_alter_documento_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField(help_text='Año del balance sheet', verbose_name='Año')),
                ('solo_usd', models.BooleanField(default=True, help_text='Indica si el balance sheet está únicamente en USD', verbose_name='Solo USD')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='contrapartes.contraparte', verbose_name='Contraparte')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Balance Sheet',
                'verbose_name_plural': 'Balance Sheets',
                'ordering': ['-año'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del item del balance', max_length=255, verbose_name='Descripción')),
                ('nota', models.TextField(blank=True, help_text='Notas adicionales sobre el item', null=True, verbose_name='Nota')),
                ('categoria', models.CharField(choices=[('assets', 'Assets'), ('liabilities', 'Liabilities'), ('equity', 'Equity')], max_length=20, verbose_name='Categoría')),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Monto en dólares estadounidenses', max_digits=20, verbose_name='Monto USD')),
                ('monto_local', models.DecimalField(blank=True, decimal_places=2, help_text='Monto en moneda local (opcional)', max_digits=20, null=True, verbose_name='Monto Moneda Local')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización del item', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('balance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contrapartes.balancesheet', verbose_name='Balance Sheet')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheet_items_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Item de Balance Sheet',
                'verbose_name_plural': 'Items de Balance Sheet',
                'ordering': ['categoria', 'orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la moneda (ISO 4217) - ej: USD, EUR, COP', max_length=3, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre de la moneda', max_length=100, verbose_name='Nombre')),
                ('simbolo', models.CharField(help_text='Símbolo de la moneda - ej: $, €, ¥', max_length=10, verbose_name='Símbolo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monedas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='moneda_local',
            field=models.ForeignKey(blank=True, help_text='Moneda local del balance sheet (opcional si es en USD)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheets_moneda_local', to='contrapartes.moneda', verbose_name='Moneda Local'),
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_usd', models.DecimalField(decimal_places=6, help_text='Cuántos USD equivale 1 unidad de esta moneda', max_digits=15, verbose_name='Tasa a USD')),
                ('fecha', models.DateField(help_text='Fecha del tipo de cambio', verbose_name='Fecha')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_cambio_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_cambio', to='contrapartes.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ['-fecha'],
                'unique_together': {('moneda', 'fecha')},
            },
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='tipo_cambio',
            field=models.ForeignKey(blank=True, help_text='Tipo de cambio utilizado para convertir a USD', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_sheets', to='contrapartes.tipocambio', verbose_name='Tipo de Cambio'),
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('contraparte', 'año')},
        ),
    ]
