# Generated by Django 5.2.4 on 2025-09-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0028_balancesheet_balancesheetitem_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', help_text='Indica si la calificación es nacional o internacional', max_length=15, verbose_name='Tipo de Calificación'),
        ),
    ]
