# Generated by Django 5.0.7 on 2025-09-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0029_calificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional'), ('no aplica', 'No aplica')], default='no aplica', help_text='Indica si la calificación es nacional o internacional', max_length=15, verbose_name='Tipo de Calificación'),
        ),
    ]
