# Generated by Django 5.2.4 on 2025-09-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0030_alter_calificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(help_text='Fecha de la calificación', verbose_name='Fecha'),
        ),
    ]
