# Generated by Django 5.0.7 on 2025-06-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_dd_completada', models.BooleanField(default=True, verbose_name='Email al completarse DD')),
                ('email_coincidencias', models.BooleanField(default=True, verbose_name='Email por coincidencias encontradas')),
                ('email_dd_proxima', models.BooleanField(default=True, verbose_name='Email por DD próxima a vencer')),
                ('email_resumen_diario', models.BooleanField(default=False, verbose_name='Resumen diario por email')),
                ('notif_dd_completada', models.BooleanField(default=True, verbose_name='Notificación en sistema al completarse DD')),
                ('notif_coincidencias', models.BooleanField(default=True, verbose_name='Notificación por coincidencias')),
                ('notif_dd_proxima', models.BooleanField(default=True, verbose_name='Notificación por DD próxima')),
                ('dias_aviso_dd', models.PositiveIntegerField(default=30, verbose_name='Días de aviso antes de vencimiento DD')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dd_completada', 'Debida Diligencia Completada'), ('dd_fallida', 'Debida Diligencia Fallida'), ('coincidencia_encontrada', 'Coincidencia Encontrada'), ('dd_proxima', 'Debida Diligencia Próxima a Vencer'), ('dd_vencida', 'Debida Diligencia Vencida'), ('revision_requerida', 'Revisión Requerida'), ('aprobacion_pendiente', 'Aprobación Pendiente'), ('sistema', 'Notificación del Sistema'), ('recordatorio', 'Recordatorio')], max_length=30, verbose_name='Tipo de notificación')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('leida', models.BooleanField(default=False, verbose_name='¿Leída?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('contraparte_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de Contraparte relacionada')),
                ('miembro_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de Miembro relacionado')),
                ('debida_diligencia_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de Debida Diligencia relacionada')),
                ('url_accion', models.URLField(blank=True, null=True, verbose_name='URL de acción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('sistema', 'Sistema'), ('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=20, verbose_name='Canal de envío')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('entregada', 'Entregada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('destinatario', models.CharField(max_length=255, verbose_name='Destinatario')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='notificaciones.notificacion', verbose_name='Notificación')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_creacion'], name='notificacio_fecha_c_83839e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo'], name='notificacio_tipo_2df5d5_idx'),
        ),
    ]
