databases:
  - name: iticodv
    plan: free
    databaseName: iticodv
    user: iticodv_user

services:
  - type: web
    plan: free
    name: itico
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn itico.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: iticodv
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4