services:
  # Web Service - Django Application
  - type: web
    name: itico-web
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn itico.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: itico.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: iticodv
          property: connectionString
      - key: TIME_ZONE
        value: America/Bogota
      - key: LANGUAGE_CODE
        value: es-co
      # Email Configuration (update with your values)
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        value: ""  # Add your email
      - key: EMAIL_HOST_PASSWORD
        value: ""  # Add your email password or app password
      # External Services (update with actual URLs when available)
      - key: MAKITO_API_URL
        value: http://localhost:8080/api
      - key: MAKITO_API_KEY
        value: ""  # Add your Makito API key
      - key: AI_SERVICE_URL
        value: http://localhost:8081/api
      - key: AI_SERVICE_KEY
        value: ""  # Add your AI service key

databases:
  # PostgreSQL Database
  - name: iticodv
    region: oregon
    plan: free
    databaseName: iticodv
    user: iticodv_user