databases:
  - name: iticodv
    plan: free
    databaseName: iticodv
    user: iticodv_user
    password: xw22RiT1kTdB1f3N9og0PLGAufVuCeeu
    host: dpg-d2m8je95pdvs73bgqtjg-a
    port: 5432

services:
  - type: web
    plan: free
    name: itico
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn financiera.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: itico
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4