# Generated by Django 5.0.7 on 2025-06-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrapartes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebidaDiligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resultado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('resumen_ia', models.TextField(blank=True, null=True, verbose_name='Resumen generado por IA')),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20, null=True, verbose_name='Nivel de riesgo detectado')),
                ('comentarios_analista', models.TextField(blank=True, null=True, verbose_name='Comentarios del analista')),
                ('aprobado', models.BooleanField(blank=True, null=True, verbose_name='¿Aprobado?')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('makito_request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de solicitud en Makito')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dd_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debidas_diligencias', to='contrapartes.miembro', verbose_name='Miembro')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dd_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Debida Diligencia',
                'verbose_name_plural': 'Debidas Diligencias',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('ofac', 'OFAC (Office of Foreign Assets Control)'), ('onu', 'Lista de Sanciones de la ONU'), ('ue', 'Lista de Sanciones de la UE'), ('interpol', 'INTERPOL'), ('pep', 'Personas Expuestas Políticamente (PEP)'), ('medios', 'Búsqueda en Medios'), ('google', 'Búsqueda en Google'), ('otra', 'Otra fuente')], max_length=20, verbose_name='Fuente de búsqueda')),
                ('estado', models.CharField(choices=[('exitosa', 'Exitosa'), ('con_error', 'Con Error'), ('coincidencia_positiva', 'Coincidencia Positiva'), ('sin_coincidencias', 'Sin Coincidencias'), ('timeout', 'Tiempo Agotado')], default='exitosa', max_length=30, verbose_name='Estado de la búsqueda')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado de la búsqueda')),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='busquedas/%Y/%m/%d/', verbose_name='Documento adjunto (PDF/HTML)')),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de búsqueda')),
                ('url_fuente', models.URLField(blank=True, null=True, verbose_name='URL de la fuente')),
                ('coincidencias_encontradas', models.PositiveIntegerField(default=0, verbose_name='Número de coincidencias encontradas')),
                ('debida_diligencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas', to='debida_diligencia.debidadiligencia', verbose_name='Debida Diligencia')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'ordering': ['-fecha_busqueda'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analisis', models.CharField(choices=[('texto', 'Análisis de Texto'), ('documento', 'Análisis de Documento'), ('resumen', 'Resumen Automatizado'), ('clasificacion', 'Clasificación de Riesgo')], max_length=20, verbose_name='Tipo de análisis')),
                ('texto_analizado', models.TextField(verbose_name='Texto analizado')),
                ('resultado_analisis', models.JSONField(default=dict, verbose_name='Resultado del análisis (JSON)')),
                ('confianza', models.FloatField(default=0.0, verbose_name='Nivel de confianza (0.0 - 1.0)')),
                ('palabras_clave_detectadas', models.JSONField(default=list, verbose_name='Palabras clave detectadas')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de análisis')),
                ('debida_diligencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to='debida_diligencia.debidadiligencia', verbose_name='Debida Diligencia')),
            ],
            options={
                'verbose_name': 'Análisis de IA',
                'verbose_name_plural': 'Análisis de IA',
                'ordering': ['-fecha_analisis'],
            },
        ),
    ]
